import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { auth } from "@/lib/auth";
import { SessionProvider } from "next-auth/react";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className={`${inter.className} bg-gradient-to-r from-blue-800 via-sky-600 to-blue-800`}>{children}</body>
      </html>
    </SessionProvider>
  );
}
